### PR TITLE
fix: clean published files

### PR DESCRIPTION
**Pull request by jaydenseric**
- Whitelist published files with a `package.json` `files` field.
  
  It's much more robust to whitelist what gets published, instead of attempting to remember to blacklist via `.npmignore` file which is now deleted.

  This change prevents [7 unnecessary files](https://unpkg.com/browse/prettier-plugin-jsdoc@0.3.30/) from being published (you can verify what gets published by running `npm pack`):

  ```diff
  - 758B   .github/workflows/test.yml
  - 101B   .husky/commit-msg
  - 95B    .husky/pre-commit
  - 8B     .prettierignore
  - 21.8kB CHANGELOG.md
    1.1kB  LICENSE
    5.3kB  README.md
  - 70B    commitlint.config.js
    325B   lib/create-language.js
    10.1kB lib/descriptionFormatter.js
    6.8kB  lib/index.js
    16.0kB lib/parser.js
    4.4kB  lib/roles.js
    4.4kB  lib/stringify.js
    3.5kB  lib/tags.js
    77B    lib/types.js
    9.0kB  lib/utils.js
    2.0kB  package.json
  - 5.7kB  tsconfig.json
  ```
- Prevent dev tool config from being published in `package.json`. It's best practice to keep dev tool config out of the `package.json` to reduce the published size of the package, in turn reducing the installed size of the package in user’s `node_modules`.
  - Prevent Husky config from being published in `package.json`.
  - Prevent Jest config from being published in `package.json`.
  
    The Jest config is in a `.js` file as it doesn't automatically respect a `.jestrc.json` file without having to use a `--config` CLI argument, but at least the Jest config can now be type checked.

    Also, a forward slash in a regex in the Jest config is now correctly escaped.

  There is still a `package.json` `workspaces` field that looks sketchy, but I figured messing around with Yarn and stuff might be too contentious for this PR.

### CODE REVIEW

**Comment by hosseinmd** [comment]
Awesome
could you add changelog to whitelist

**Comment by hosseinmd** [comment]
Is that good for SEO?

**Comment by jaydenseric** [comment]
It's desirable not to publish the changelog so that the install size of the package is stable and it doesn't keep growing limitlessly over time as new versions are added to the changelog. Changelogs can become quite big.

It's safe to not publish the changelog, as no-one reads the it from within `node_modules`. NPM no longer forces `CHANGELOG.md` to be published. NPM still forces `README.md` to be published, but I think that's because there is a chance that it contains the software license.

The changelog versioned in the GitHub repo is a better reference for users to read, as any corrections for past version changelog entries (updates to broken links, adding missing changes, etc.) can be seen whereas the changelogs published to npm are frozen in time and can't be amended.

Let me know if you are still sure you want to publish the changlog and I'll update this PR :)

> Is that good for SEO?

Sorry, I'm not sure exactly what you're referring to as "that".

**Comment by hosseinmd** [comment]
Thank you.

**Pull request merged**
