### PR TITLE
fix: editorconfig indent_style=tab breaking example tag

### PR DESCRIPTION
**Pull request by danielpza**
Closes https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/109

All tests pass I'm not sure if by removing this match in the regexp somethings breaks. Can you confirm on the intent of this part of the regexp @hosseinmd?

Also didn't add any extra tests because wasn't sure how to add an editorconfig in a folder with the test file in the current configuration, however I did test it in a sandbox and seems to be working

### CODE REVIEW

**Comment by hosseinmd** [comment]
Please add your example to tests

**Comment by hosseinmd** [comment]
i rebase master. to your branch

**Comment by danielpza** [comment]
> Please add your example to tests

@hosseinmd I don't think the tests are picking up the .editorconfig options, so I don't know how to add it to test

**Review by hosseinmd — APPROVED** [review]

**Comment by hosseinmd** [comment]
Thank you.

**Pull request merged**
