### PR TITLE
fix: ensure formatting matches Prettier markdown formatter

### LINKED ISSUE #142: Consider using underlines for italics instead of stars to be consistent with prettier's markdown formatting
It didn't really click until today, but currently this plugin converts `_words_` into `*words*` - personally I'm not too fussed by that, except Prettier does the opposite in it's markdown formatter (I think to make it more distinctive vs bold) and I feel like it would be good to be consistent since jsdoc comments are often treated as markdown (at least for formatting).

afaik both `_words_` & `*words*` are allowed in JSDoc for italics, but I also could be wrong.

Happy to implement a PR (both just changing it or adding an option) if you want to see this change :)

### PR DESCRIPTION
**Pull request by G-Rath**
Fixes #142

Have also added a test using the sample markdown the Prettier playground uses, to ensure the formatting remains consistent.

### CODE REVIEW

**Comment by G-Rath** [comment]
CI failure looks unrelated to this change:

```
error An unexpected error occurred: "could not find a copy of prettier to link in /home/runner/work/prettier-plugin-jsdoc/prettier-plugin-jsdoc/node_modules/@react-native-community/eslint-config/node_modules".
```

**Comment by hosseinmd** [comment]
> CI failure looks unrelated to this change:
> 
> ```
> error An unexpected error occurred: "could not find a copy of prettier to link in /home/runner/work/prettier-plugin-jsdoc/prettier-plugin-jsdoc/node_modules/@react-native-community/eslint-config/node_modules".
> ```

This error occur in last version of prettier, last version of prettier

**Review by hosseinmd — APPROVED** [review]
Good

**Comment by hosseinmd** [comment]
mdast-util-from-markdown has few updated. But i don't know how we can migrate to new version because new version is esm module. Do you have a solution for this?

**Comment by G-Rath** [comment]
@hosseinmd do you need to update `mdast-util-from-markdown`? and if so, what is it being used for?

The solutions I know of are:
  * import the module using dynamic `import(...)`
    * this is async, so requires the caller (in this case `prettier`) to support being given a promise, which I don't think it does
  * vendor the dependency as part of the published package, which'd allow you to transpile it into non-esm
  * switch to another package
  * switch this package to ESM
    * this can't be done because then this package would be async, which prettier doesn't support

I think the quickest one would be to transpile and vendor the dependency, but the ideal would be switching to another package if possible.

**Comment by hosseinmd** [comment]
We used this package to convert description md string to a model. I don't know another package to do this. Now this package growing, but I can't use new versions. Convert package into non-esm is a good idea, but i don't know how can i do it.

**Comment by Sxxov** [comment]
@hosseinmd have you looked into using a loader?

here's an example of using [`esm`](https://www.npmjs.com/package/esm) to load esmodules into a commonjs environment:
```js
const fromMarkdown = require('esm')(module)('mdast-util-from-markdown');
```

**Comment by G-Rath** [comment]
@Sxxov I didn't think about using a sync loader to handle this - not sure how much of a fan I am of it but it probably is fine. It looks like `esm` is unmaintained, but I'll hunt around to see if there's another loader that could do the job.

@hosseinmd if you want to create a new issue for this and assign it to me, I'll try and get a solution together (either by transpiling/vendoring or now maybe using a loader). I'm assuming this isn't critical, so will probably get into it next week once I've cleared a few other things on my plate 🙂

**Comment by hosseinmd** [comment]
> @hosseinmd have you looked into using a loader?
> 
> here's an example of using [`esm`](https://www.npmjs.com/package/esm) to load esmodules into a commonjs environment:
> 
> ```js
> const fromMarkdown = require('esm')(module)('mdast-util-from-markdown');
> ```

I created an issue for this  https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/150

**Pull request merged**
