### PR TITLE
fix: the "caption" should place behind the tag of "example"

### PR DESCRIPTION
**Pull request by Aqzhyi**
before

```tsx
/**
 * @example
 *   ;<caption>A Script that can fetch the new data</caption>
 *
 *   const remoteSupportSymbols = await fetch(URL).then(res => res.json())
 *
 *   globalThis.foo = keyBy(
 *     remoteSupportSymbols.filter(value => value.type !== 'option').map(value => camelizeKeys(value)),
 *     'symbol',
 *   )
 *
 *   console.info(globalThis.foo)
 */
```

with this PR

```tsx
/**
 * @example <caption>A Script that can fetch the new data</caption>
 *
 *   const remoteSupportSymbols = await fetch(URL).then(res => res.json())
 *
 *   globalThis.foo = keyBy(
 *     remoteSupportSymbols.filter(value => value.type !== 'option').map(value => camelizeKeys(value)),
 *     'symbol',
 *   )
 *
 *   console.info(globalThis.foo)
 */
```

### CODE REVIEW

**Comment by hosseinmd** [comment]
Good stuff.

**Comment by hosseinmd** [comment]
There is a problem with tow caption component in example

Please test this
```js
  /**
   * @example <caption>TradingViewChart</caption>;
   *
   * const Something(){
   *   return <caption>TradingViewChart</caption>
   * }
   * export default Something
   */
```

**Comment by hosseinmd** [comment]
Done, is will merge this if you approve

**Review by hosseinmd — APPROVED** [review]

**Comment by Aqzhyi** [comment]
looks working fine in my projects

good to see to merge

**Pull request merged**
