### PR TITLE
fix: not working for multi line union types

### LINKED ISSUE #16: Not formatting typescript union correctly
Input:

```js
/** @type {{ foo: string } | { bar: string; manyMoreLongArguments: object } | { baz: string }} */
const a = {};
```

Expected:

```js
/**
 * @type {  
 *   | { foo: string }
 *   | { bar: string; manyMoreLongArguments: object }
 *   | { baz: string }
 * }
 */
const a = {};
```

Result:

```js
/**
 * @type {  | { foo: string }
 *   | { bar: string; manyMoreLongArguments: object }
 *   | { baz: string }}
 */
const a = {};
```

### PR DESCRIPTION
**Pull request by danielpza**
closes #16

### CODE REVIEW

**Comment by hosseinmd** [comment]
Good stuff. Thanks.

**Comment by hosseinmd** [comment]
release: 0.2.9 https://github.com/hosseinmd/prettier-plugin-jsdoc/commit/31ba3e47855f5cb5200977c40e66ee914d4dc871

**Comment by sgtpep** [comment]
Hey! I've run into an issue with this change. Once the @type is formatted this way (no symbols after `@type {` on the same line), typescript treats such a type as any (ignores it?). Had to stick my dependency to 0.2.8 because of that.

**Comment by hosseinmd** [comment]
Can I see your code?

**Comment by sgtpep** [comment]
```typescript
/**
 * @type {
 *   | ((
 *       foo: Foo,
 *       bar: Bar,
 *       baz: Baz,
 *       qux: Qux,
 *     ) => void)
 *   | undefined}
 */
export let orderMocked;

/** @type {(mockOrdering: typeof orderMocked) => void} */
const mockOrdering = (mockOrdering) => {};

/** @type {Parameters<typeof mockOrdering>[0]} */
const handleOrdering = (
  foo,
  bar,
  baz,
  qux
) => {}
```

Maybe it's a bug in TypeScript, but if there's a newline after `@type {`, but it throws an error that arguments of the last functions are of type `any`.

**Comment by hosseinmd** [comment]
Yes you are right. I say that bug, I think this change should be reverted.

But I need to know what @danielpza think.

**Comment by danielpza** [comment]
> But I need to know what @danielpza think.
agree.

**Pull request merged**
