### PR TITLE
style: add config to the .prettierrc based on style of current codebase

### PR DESCRIPTION
**Pull request by Aqzhyi**
So the people who wanna join this project, able to align on the same config of the prettier based on this project scope.

### CODE REVIEW

**Comment by hosseinmd** [comment]
I don't think so because prettier defining default config based on best practices and maybe they change default config in the future. The best way for this plugin is to follow the prettier default config.

**Comment by hosseinmd** [comment]
We don't want to change project codes after added this plugin, The aim of this plugin is to work just on comments (jsdoc).

**Comment by hosseinmd** [comment]
But I think you have a more convincing reason for this.

**Comment by Aqzhyi** [comment]
This project is helping me save the time, so I want to try to do some contribute as I can. I have other projects that also use prettier.

So, my settings are `"prettier.requireConfig": true`, if no the settings, my prettier format that code into the difference with your project. It breaks my dig.

So I am according to your codebase set up some configs, I thought it might not breaking your format config.

What do you think?

**Comment by hosseinmd** [comment]
I am not sure, but I merge this PR. maybe we discuss this in the future.

thank you.

**Pull request merged**
