### PR TITLE
feat: add option to turn off capitalization

### PR DESCRIPTION
**Pull request by vostrnad**
Hello!

This plugin is exactly what I need, except for one little detail: It runs into some false positives when trying to capitalize descriptions. Rather than adding more exceptions, the only one currently being links starting with `http(s)://`, I propose an option called `jsdocCapitalizeDescription` that would enable users to turn off capitalization altogether.

### CODE REVIEW

**Comment by jaydenseric** [comment]
Because auto capitalization can be considered destructive, IMO it should be opt-in, not opt-out.

@hosseinmd can we please release this feature? It seems it hasn't been published yet…

**Comment by vostrnad** [comment]
I made this opt-out so it wouldn't be a breaking change, but I agree that this should definitely be made opt-in in a future breaking release. (Maybe this isn't even a concern as this package is still major version 0.)

And yes, could you create a new release @hosseinmd?

**Review by hosseinmd — COMMENTED** [review]
.

**Comment by hosseinmd** [comment]
Yes, I think this could be release as path version.

**Comment by hosseinmd** [comment]
https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/master/CHANGELOG.md#0325-2021-11-05

**Comment by hosseinmd** [comment]
Released in v0.3.25

**Pull request merged**
